// Movies.js
const movies = [
  {
    id: 1,
    name: "Salaar (2023)",
    title: "Salaar",
    image: require("../assets/images/salaar.jpeg"),
    media: require("../assets/images/salaar_bw.jpeg"),
    media2: require("../assets/images/salaar_bw2.jpeg"),
    caption: "added a new video",
    caption2: "added a new photo",
    challenge: "added a new challenge",
    challenge1: "Walk 1000 steps",
    challenge2: "How well do you know prabhas?",
    challengeType1: "stepCounter",
    challengeType2: "quiz",
  },
  {
    id: 2,
    name: "Dunki (2023)",
    title: "Dunki",
    image: require("../assets/images/dunki.jpeg"),
    media: require("../assets/images/dunki_bw.jpeg"),
    media2: require("../assets/images/dunki_bw2.jpeg"),
    caption: "added a new photo",
    caption2: "added a new photo",
    challenge: "added a new challenge",
    challenge1: "Walk 1000 steps",
    challenge2: "How well do you know SRK?",
    challengeType1: "stepCounter",
    challengeType2: "quiz",
  },
  {
    id: 3,
    name: "Wonka (2023)",
    title: "Wonka",
    image: require("../assets/images/wonka.jpeg"),
    media: require("../assets/images/wonka_bw.jpeg"),
    media2: require("../assets/images/wonka_bw2.jpeg"),
    caption: "added a new video",
    caption2: "added a new photo",
    challenge: "added a new challenge",
    challenge1: "Walk 1000 steps",
    challenge2: "How well do you know timothee chalamet?",
    challengeType1: "stepCounter",
    challengeType2: "quiz",
  },
  {
    id: 4,
    name: "Kalki (2024)",
    title: "Kalki",
    image: require("../assets/images/kalki.jpeg"),
    media: require("../assets/images/kalki_bw.jpeg"),
    media2: require("../assets/images/kalki_bw2.jpeg"),
    caption: "added a new video",
    caption2: "added a new photo",
    challenge: "added a new challenge",
    challenge1: "Walk 1000 steps",
    challenge2: "How well do you know prabhas?",
    challengeType1: "stepCounter",
    challengeType2: "quiz",
  },
  {
    id: 5,
    name: "Pushpa-2 (2024)",
    title: "Pushpa-2",
    image: require("../assets/images/pushpa2.jpeg"),
    media: require("../assets/images/pushpa2_bw.jpeg"),
    media2: require("../assets/images/pushpa2_bw2.jpeg"),
    caption: "added a new photo",
    caption2: "added a new photo",
    challenge: "added a new challenge",
    challenge1: "Walk 1000 steps",
    challenge2: "How well do you know Allu Arjun?",
    challengeType1: "stepCounter",
    challengeType2: "quiz",
  },
  {
    id: 6,
    name: "Hi Nanna (2023)",
    title: "Hi Nanna",
    image: require("../assets/images/nanna.jpeg"),
    media: require("../assets/images/hinanna_bw.jpeg"),
    media2: require("../assets/images/hinanna_bw2.jpeg"),
    caption: "added a new photo",
    caption2: "added a new photo",
    challenge: "added a new challenge",
    challenge1: "Walk 1000 steps",
    challenge2: "How well do you know Nani?",
    challengeType1: "stepCounter",
    challengeType2: "quiz",
  },
];

export default movies;
